# Stage 1: Build
FROM golang:1.19-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod init example/hello && go mod tidy
# Add ldflags to strip debug information
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -v -o /app/main .

# Stage 2: Minimalist
FROM scratch
COPY --from=builder /app/main /main
EXPOSE 8080
CMD ["/main"]
